### ISSUE TITLE
wp-content folder not writable by wordpress

### ISSUE THREAD

**Issue by gregnemes** [work-shop/lri-backend#1]
I'm unable to update plugins, import data for WP All Import, or use features that write new files to the server.

**Comment by nicschumann** [comment]
This problem is being caused by the parent Wordpress directory not being appropriately permissioned. I've updated the permissions for LRI, and am able to install and update plugins. Please test with `WP All Import` and test whether the issue is corrected.

**Comment by gregnemes** [comment]
WP All import working correctly, and I made a change to the theme code and deployed it, and the permissions still work.
